global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prom_counter
    # metrics defaults to '/metrics'
    # scheme defaults to 'http'
    static_configs:
      - targets: ['counter:8085'] # metrics port
