global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: http_test
    # metrics defaults to '/metrics'
    # scheme defaults to 'http'
    static_configs:
      - targets: ['server:8080'] # multiplexed into the main port
